spring:
  application:
    name: "spring-ai-demo"

  ai:
    openai:
      chat:
        options:
          model: "gpt-4o"
      api-key: ${OPEN_API_KEY}

#logging:
#  level:
#    org:
#      springframework:
#        ai:
#          chat:
#            client:
#              advisor:
#                SimpleLoggerAdvisor: debug